---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.10

suites:
  - name: default
    run_list:
    - recipe[machine-setup::default]
    - recipe[user-files::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
