---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.10

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chef_vault:
        databag_fallback: true
