---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    attributes:
      chef_vault:
        databag_fallback: true
